name: tracker
description: A new Flutter aplication on fatching covid-19 cases


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  http: ^0.12.1
  time_formatter: ^1.0.0

  cupertino_icons: ^0.1.3
  number_slide_animation: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
